{% set name = "tweedledum" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/boschmitt/tweedledum/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ba1c79808dfae1cf65a06eb6c5aeee4daf9e826386c582b5fea0c5c634f4d15b

build:
  number: 1
  skip: True  # [win]
  script:
    - export CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"   # [osx]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - cmake >=3.18
    - make
    - ninja
  host:
    - eigen
    - pip
    - python
    - setuptools >=42
    - wheel
    - scikit-build >=0.12.0
  run:
    - python

test:
  imports:
    - tweedledum
    - tweedledum.bool_function_compiler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/boschmitt/tweedledum
  summary: A library for synthesizing and manipulating quantum circuits
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
